export const WITHDRAWAL_REQUEST="WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS="WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE="WITHDRAWAL_FAILURE";



export const GET_WITHDRAWAL_HISTORY_REQUEST="GET_WITHDRAWAL_HISTORY_REQUEST";
export const GET_WITHDRAWAL_HISTORY_SUCCESS="GET_WITHDRAWAL_HISTORY_SUCCESS";
export const GET_WITHDRAWAL_HISTORY_FAILURE="GET_WITHDRAWAL_HISTORY_FAILURE";
